name: Build

on: [pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false
      - name: Add init script
        run: |
          cat << 'EOF' > $GRADLE_USER_HOME/init.d/testlens-init.gradle
          gradle.settingsEvaluated { settings ->
            settings.dependencyResolutionManagement.repositories {
              maven { 
                url = 'https://central.sonatype.com/repository/maven-snapshots'
              }
            }
          }
          gradle.allprojects {
            plugins.withId('java') {
              testing.suites.configureEach {
                dependencies { runtimeOnly('app.testlens:junit-platform-instrumentation:0.1.0-SNAPSHOT') }
              }
            }
            tasks.withType(Test).configureEach {
              systemProperty('app.testlens.project-id', '${{ github.repository }}')
              systemProperty('app.testlens.token', 'ab9993fd-f021-4806-9125-633e66357af6')
              systemProperty('app.testlens.server-address', '${{ vars.TESTLENS_SERVER }}')
              systemProperty('app.testlens.use-plaintext', '${{ vars.GRPC_PLAINTEXT }}')
            }
          }
          EOF
      - run: ./gradlew build
        env:
          GITHUB_TOKEN: ${{ secrets.TESTLENS_BOT_GITHUB_TOKEN }}
