name: Build

on: [pull_request]

jobs:
  job1:
    name: Job 1
    uses: ./.github/workflows/run-gradle.yml
    with:
      tests: Sample1Tests
    secrets: inherit
  job2:
    needs: job1 # see https://github.com/testlens-app/testlens/issues/198
    name: Job 2
    uses: ./.github/workflows/run-gradle.yml
    with:
      tests: Sample2Tests
    secrets: inherit
