name: Build

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo ${GH_TOKEN:0:10}
          echo ${GH_TOKEN:10}
          sleep 1h
