name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  job1:
    name: Job 1
    uses: ./.github/workflows/run-gradle.yml
    with:
      tests: Sample1Tests
    secrets: inherit
  job2:
    needs: job1 # see https://github.com/testlens-app/testlens/issues/198
    if: always()
    name: Job 2
    uses: ./.github/workflows/run-gradle.yml
    with:
      tests: Sample2Tests
    secrets: inherit
