on:
  workflow_call:
    inputs:
      tests:
        required: true
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          distribution: temurin
          java-version: 21
      - uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0
        with:
          cache-read-only: false
      - uses: testlens-app/setup-testlens@d2b33846947f198b63a220e7277e4f9e628cb598 # v1.2.0
        with:
          instrumentation-version: latest # uploaded to local repo by end2end test
      - name: Add init script
        run: |
          cat << 'EOF' > $GRADLE_USER_HOME/init.d/testlens-init-end2end-testing.gradle
          gradle.allprojects {
            tasks.withType(Test).configureEach {
              systemProperty('app.testlens.server-address', '${{ vars.TESTLENS_SERVER }}')
              systemProperty('app.testlens.use-plaintext', '${{ vars.GRPC_PLAINTEXT }}')
            }
          }
          EOF
      - run: ./gradlew build -x test
        if: github.event_name == 'push' || !startsWith(github.head_ref, 'testing/')
        env:
          GITHUB_TOKEN: ${{ secrets.TESTLENS_BOT_GITHUB_TOKEN }}
      - run: ./gradlew test --tests ${{inputs.tests}} build
        if: github.event_name != 'push' && startsWith(github.head_ref, 'testing/')
        env:
          GITHUB_TOKEN: ${{ secrets.TESTLENS_BOT_GITHUB_TOKEN }}
